export const FOOD_DATA = [
  {
    id: 'apple',
    nameZh: '蘋果',
    nameEn: 'Apple',
    synonyms: ['apple', 'granny smith', 'red delicious'],
    defaultServing: {
      label: '中型蘋果 (182g)',
      grams: 182,
    },
    per100g: {
      calories: 52,
      protein: 0.3,
      fat: 0.2,
      carbs: 14,
    },
  },
  {
    id: 'banana',
    nameZh: '香蕉',
    nameEn: 'Banana',
    synonyms: ['banana', 'plantain'],
    defaultServing: {
      label: '中型香蕉 (118g)',
      grams: 118,
    },
    per100g: {
      calories: 89,
      protein: 1.1,
      fat: 0.3,
      carbs: 23,
    },
  },
  {
    id: 'orange',
    nameZh: '橙子',
    nameEn: 'Orange',
    synonyms: ['orange', 'clementine'],
    defaultServing: {
      label: '中型橙 (131g)',
      grams: 131,
    },
    per100g: {
      calories: 47,
      protein: 0.9,
      fat: 0.1,
      carbs: 12,
    },
  },
  {
    id: 'strawberry',
    nameZh: '草莓',
    nameEn: 'Strawberry',
    synonyms: ['strawberry'],
    defaultServing: {
      label: '一杯草莓 (152g)',
      grams: 152,
    },
    per100g: {
      calories: 32,
      protein: 0.7,
      fat: 0.3,
      carbs: 8,
    },
  },
  {
    id: 'watermelon',
    nameZh: '西瓜',
    nameEn: 'Watermelon',
    synonyms: ['watermelon'],
    defaultServing: {
      label: '一片西瓜 (280g)',
      grams: 280,
    },
    per100g: {
      calories: 30,
      protein: 0.6,
      fat: 0.2,
      carbs: 8,
    },
  },
  {
    id: 'broccoli',
    nameZh: '花椰菜',
    nameEn: 'Broccoli',
    synonyms: ['broccoli'],
    defaultServing: {
      label: '一杯花椰菜 (91g)',
      grams: 91,
    },
    per100g: {
      calories: 34,
      protein: 2.8,
      fat: 0.4,
      carbs: 7,
    },
  },
  {
    id: 'carrot',
    nameZh: '紅蘿蔔',
    nameEn: 'Carrot',
    synonyms: ['carrot'],
    defaultServing: {
      label: '一根紅蘿蔔 (61g)',
      grams: 61,
    },
    per100g: {
      calories: 41,
      protein: 0.9,
      fat: 0.2,
      carbs: 10,
    },
  },
  {
    id: 'tomato',
    nameZh: '番茄',
    nameEn: 'Tomato',
    synonyms: ['tomato'],
    defaultServing: {
      label: '中型番茄 (123g)',
      grams: 123,
    },
    per100g: {
      calories: 18,
      protein: 0.9,
      fat: 0.2,
      carbs: 3.9,
    },
  },
  {
    id: 'cucumber',
    nameZh: '小黃瓜',
    nameEn: 'Cucumber',
    synonyms: ['cucumber'],
    defaultServing: {
      label: '半條小黃瓜 (100g)',
      grams: 100,
    },
    per100g: {
      calories: 16,
      protein: 0.7,
      fat: 0.1,
      carbs: 3.6,
    },
  },
  {
    id: 'avocado',
    nameZh: '酪梨',
    nameEn: 'Avocado',
    synonyms: ['avocado'],
    defaultServing: {
      label: '半顆酪梨 (100g)',
      grams: 100,
    },
    per100g: {
      calories: 160,
      protein: 2,
      fat: 15,
      carbs: 9,
    },
  },
  {
    id: 'egg',
    nameZh: '雞蛋',
    nameEn: 'Egg',
    synonyms: ['fried egg', 'poached egg', 'omelette', 'scrambled eggs', 'egg'],
    defaultServing: {
      label: '一顆大雞蛋 (50g)',
      grams: 50,
    },
    per100g: {
      calories: 155,
      protein: 13,
      fat: 11,
      carbs: 1.1,
    },
  },
  {
    id: 'chicken-breast',
    nameZh: '雞胸肉',
    nameEn: 'Chicken Breast',
    synonyms: ['chicken breast', 'grilled chicken', 'roasted chicken'],
    defaultServing: {
      label: '煮熟雞胸肉 (120g)',
      grams: 120,
    },
    per100g: {
      calories: 165,
      protein: 31,
      fat: 3.6,
      carbs: 0,
    },
  },
  {
    id: 'salmon',
    nameZh: '鮭魚',
    nameEn: 'Salmon',
    synonyms: ['salmon'],
    defaultServing: {
      label: '烤鮭魚 (154g)',
      grams: 154,
    },
    per100g: {
      calories: 208,
      protein: 20,
      fat: 13,
      carbs: 0,
    },
  },
  {
    id: 'beef-steak',
    nameZh: '牛排',
    nameEn: 'Beef Steak',
    synonyms: ['steak', 'beefsteak', 'sirloin', 'ribeye'],
    defaultServing: {
      label: '煎牛排 (150g)',
      grams: 150,
    },
    per100g: {
      calories: 271,
      protein: 25,
      fat: 19,
      carbs: 0,
    },
  },
  {
    id: 'tofu',
    nameZh: '豆腐',
    nameEn: 'Tofu',
    synonyms: ['tofu'],
    defaultServing: {
      label: '板豆腐 (126g)',
      grams: 126,
    },
    per100g: {
      calories: 76,
      protein: 8,
      fat: 4.8,
      carbs: 1.9,
    },
  },
  {
    id: 'yogurt',
    nameZh: '優格',
    nameEn: 'Plain Yogurt',
    synonyms: ['yogurt', 'greek yogurt'],
    defaultServing: {
      label: '一杯優格 (245g)',
      grams: 245,
    },
    per100g: {
      calories: 59,
      protein: 10,
      fat: 0.4,
      carbs: 3.6,
    },
  },
  {
    id: 'almonds',
    nameZh: '杏仁',
    nameEn: 'Almonds',
    synonyms: ['almond'],
    defaultServing: {
      label: '一把杏仁 (28g)',
      grams: 28,
    },
    per100g: {
      calories: 579,
      protein: 21,
      fat: 50,
      carbs: 22,
    },
  },
  {
    id: 'rice',
    nameZh: '白飯',
    nameEn: 'Cooked White Rice',
    synonyms: ['white rice', 'steamed rice'],
    defaultServing: {
      label: '一碗白飯 (158g)',
      grams: 158,
    },
    per100g: {
      calories: 130,
      protein: 2.4,
      fat: 0.3,
      carbs: 28,
    },
  },
  {
    id: 'pasta',
    nameZh: '義大利麵',
    nameEn: 'Cooked Pasta',
    synonyms: ['pasta', 'spaghetti', 'macaroni'],
    defaultServing: {
      label: '一杯義大利麵 (140g)',
      grams: 140,
    },
    per100g: {
      calories: 131,
      protein: 5,
      fat: 1.1,
      carbs: 25,
    },
  },
  {
    id: 'bread',
    nameZh: '吐司',
    nameEn: 'White Bread Slice',
    synonyms: ['bread', 'toast'],
    defaultServing: {
      label: '一片吐司 (28g)',
      grams: 28,
    },
    per100g: {
      calories: 266,
      protein: 8.9,
      fat: 3.3,
      carbs: 49,
    },
  },
  {
    id: 'sweet-potato',
    nameZh: '地瓜',
    nameEn: 'Sweet Potato',
    synonyms: ['sweet potato', 'yam'],
    defaultServing: {
      label: '中型地瓜 (130g)',
      grams: 130,
    },
    per100g: {
      calories: 86,
      protein: 1.6,
      fat: 0.1,
      carbs: 20,
    },
  },
  {
    id: 'cheddar-cheese',
    nameZh: '切達起司',
    nameEn: 'Cheddar Cheese',
    synonyms: ['cheddar', 'cheese'],
    defaultServing: {
      label: '一片起司 (28g)',
      grams: 28,
    },
    per100g: {
      calories: 403,
      protein: 25,
      fat: 33,
      carbs: 1.3,
    },
  },
];
